export const APIROUTES = {
  LOGIN: "/OcufiiDynamoDB/Login",
  GET_ACTIVE_ALERTS: (email, limit, dateRange = "24 hours") =>
    `/Dashboard/GetActiveAlerts?email=${email}&dateRange=${dateRange}&limit=${limit}`,
  PING_RECIPIENTS: "/Dashboard/PingSafetyNetworkLocations",
  GET_SAFETY_NETWORK_LOCATIONS: (email, notificationId, senderEmail) =>
    `/Dashboard/GetSafetyNetworkLocations?email=${email}&notificationId=${notificationId}&senderEmail=${senderEmail}`,  
  SEND_ASSIST_MESSAGE: "/Dashboard/SendAssistMessage",
  GET_ASSIST_REQUEST_STATUS: (notificationId) =>
    `/Dashboard/GetAssistRequestStatus?notificationId=${notificationId}`,
  SHARE_ROUTE: "/Dashboard/SendRouteToMember",
  GET_ALERT_SUMMARY: "/Dashboard/GetAlertSummary",
  GET_DEVICE_HEALTH: (email) => `/Dashboard/GetDeviceHealth?email=${email}`,
  GET_ALERT_NOTES: (email, notificationId) =>
    `/Dashboard/GetAlertNotes?email=${email}&notificationId=${notificationId}`,
  ADD_ALERT_NOTES: "/Dashboard/AddAlertNote",
  GET_ALL_DEVICES: (email) =>
    `/Dashboard/devices/all?email=${email}&filter=all`,
  GET_OVERVIEW_STATS: (email) => `/Dashboard/GetOverview?email=${email}`,
  SEND_MESSAGE_TO_VICTIM: "/Dashboard/SendMessageToVictim",
  SET_SNOOZE: "/Dashboard/devices/snooze/start",
  STOP_SNOOZE: "/Dashboard/devices/snooze/stop",
  DELETE_ACCOUNT: "/Email/DeleteAccount",
  UPDATE_USERNAME: "/OcufiiDynamoDB/UpdateUsername",
  GET_RECIPIENTS: (email) => `/UserNotify/GetRecipients?email=${email}`,
  GET_SAFETY_NETWORK_MEMBERS: (email) =>
    `/SafetyLink/GetMembers?email=${email}`,
  GET_SAFETY_NETWORK_MEMBER_DETAILS: (email, memberEmail) =>
    `/SafetyLink/GetLinkDetails?email=${email}&linkedMember=${memberEmail}`,
  GET_USER_SETTINGS: (email) => `/Dashboard/settings?email=${email}`,
  PING_MEMBER: "/Dashboard/PingMemberLocations",
  GET_MEMBER_LOCATIONS: (email) =>
    `/Dashboard/GetMemberLocations?email=${email}`,
  DELETE_NOTIFICATIONS: (email) => `/Dashboard/Notifications/${email}`,
  LINK_FAMILY_NETWORK: "/SafetyLink/LinkFamilyNetwork",
  VERIFY_OTP: "/SafetyLink/VerifyOTP",
  DELETE_MEMBER: "/SafetyLink/DeleteMember",
  RESEND_INVITATION: "/SafetyLink/ResendInvitation",
  INVITE_SAFETY_MEMBER: "/Email/InviteSafetyMember",
  UPDATE_MEMBER: "/SafetyLink/UpdateMember",
  CHANGE_STATUS: "/SafetyLink/ChangeStatus",
  SEND_NOTIFICATION: "/SafetyLink/SendNotification",
  UPDATE_SETTING_911: "/Dashboard/settings/emergency-911",
  UPDATE_SETTING_988: "/Dashboard/settings/emergency-988",
  UPDATE_SETTING_EMERGENCY: "/Dashboard/settings/emergency",
  UPDATE_SETTING_ACTIVE_SHOOTER: "/Dashboard/settings/active-shooter",
  UPDATE_SETTING_DISTRESS: "/Dashboard/settings/distress",
  UPDATE_SETTING_POLICE: "/Dashboard/settings/police",
  UPDATE_SETTING_MEDICAL: "/Dashboard/settings/emergency-medical-service",
  UPDATE_SETTING_FIRE: "/Dashboard/settings/fire-department",
  UPDATE_MOVEMENT_SOUND: "/Dashboard/settings/movement-sound",
  UPDATE_MOVEMENT_VIBRATION: "/Dashboard/settings/movement-vibration",
  UPDATE_AUTO_LOGOUT: "/Dashboard/settings/auto-logout",
  UPDATE_SOUND: "/Dashboard/settings/sound",
  UPDATE_PERSONAL_SAFETY_USERNAME: "/Dashboard/settings/personal-safety-username",
  EMAIL_ADD_RECIPIENT: "/Email/AddRecipient",
  ADD_RECIPIENT: "/UserNotify/AddRecipient",
  DELETE_RECIPIENT: "/UserNotify/DeleteRecipient",
  UPDATE_RECIPIENT: "/UserNotify/UpdateRecipient",
  SEND_RECIPIENT_NOTIFICATION: "/UserNotify/SendNotification",
  VERIFICATION_POLLING: (email, category) =>
    `/Email/VerificationPolling?email=${encodeURIComponent(email)}&category=${category}`,
  UPDATE_GATEWAY: "/OcufiiDynamoDB/UpdateGateway",
  UPDATE_BEACON: "/OcufiiDynamoDB/UpdateBeacon",
  DELETE_GATEWAY_EMAIL: "/Email/DeleteGateway",
  DELETE_GATEWAY_DIRECT: "/OcufiiDynamoDB/DeleteGateway",
  DELETE_BEACON_EMAIL: "/Email/DeleteBeacon",
  DELETE_BEACON_DIRECT: "/OcufiiDynamoDB/DeleteBeacon",
  FORGOT_PASSWORD_EMAIL: "/Email/ForgotPassword",
  CHANGE_PASSWORD_EMAIL: "/Email/ChangePassword",
  CHANGE_PASSWORD_DIRECT: "/Email/ChangePasswordDirect",
  RESET_PASSWORD: "/OcufiiDynamoDB/ForgotPassword",
  GET_TOS_ITEM: "/OcufiiDynamoDB/TermOfServiceItem",
  ACCEPT_TOS: "/OcufiiDynamoDB/AcceptTermsOfService",
  GENERATE_TOKEN: "/OcufiiDynamoDB/GenerateToken",
  VERIFY_EMAIL_SIGNUP: "/Email/VerifyEmail",
  WEBSIGNUP: "/OcufiiDynamoDB/WebSignUp",
};
