export const ROUTE = {

  LOGIN: "CustomerPortal/login",
  DASHBOARD: "CustomerPortal/dashboard",
  ALERT: "CustomerPortal/alert",
  DEVICES: "CustomerPortal/devices",
  HISTORY: "CustomerPortal/history",
  RECIPIENTS: "CustomerPortal/recipients",
  SHOP: "https://ocufiistore.com/",
  HELP: "https://www.ocufii.com/",
  DEVICEDETAILS: "CustomerPortal/device_details",
  ACCOUNT: "CustomerPortal/account",
  SETTINGS: "CustomerPortal/settings",
  ALERT_DETAILS: "CustomerPortal/alert_details",
  SAFETY_NETWORK: "CustomerPortal/safety_network",
  PERSONAL_SAFETY: "CustomerPortal/personal_safety",
  ADD_RECIPIENT: "CustomerPortal/add_new_recipient",
  RESEND_EMAIL: "CustomerPortal/resend_email",
  EMAIL_VERIFIED: "CustomerPortal/email_verified",
  INVITE_CONTACT: "CustomerPortal/invite_contact",
  ACCEPT_INVITE: "CustomerPortal/accept_inivite",
  MAP: "CustomerPortal/map",
  FORGOT_PASSWORD: "CustomerPortal/forgot-password",
  RESET_PASSWORD: "CustomerPortal/reset-password",
};
