export const ROUTE = {
  LOGIN: "/customerportal/login",
  DASHBOARD: "/customerportal/dashboard",
  ALERT: "/customerportal/alert",
  DEVICES: "/customerportal/devices",
  HISTORY: "/customerportal/history",
  RECIPIENTS: "/customerportal/recipients",
  SHOP: "https://ocufiistore.com/",
  HELP: "https://www.ocufii.com/",
  DEVICEDETAILS: "/customerportal/device_details",
  ACCOUNT: "/customerportal/account",
  SETTINGS: "/customerportal/settings",
  ALERT_DETAILS: "/customerportal/alert_details",
  SAFETY_NETWORK: "/customerportal/safety_network",
  PERSONAL_SAFETY: "/customerportal/personal_safety",
  ADD_RECIPIENT: "/customerportal/add_new_recipient",
  RESEND_EMAIL: "/customerportal/resend_email",
  EMAIL_VERIFIED: "/customerportal/email_verified",
  INVITE_CONTACT: "/customerportal/invite_contact",
  ACCEPT_INVITE: "/customerportal/accept_invite",
  MAP: "/customerportal/map",
  FORGOT_PASSWORD: "/customerportal/forgot-password",
  RESET_PASSWORD: "/customerportal/reset-password",
  SIGN_UP: "/customerportal/signup",
  ACCOUNT_SETUP: "/customerportal/account_setup",
  TERMS_OF_SERVICE_SIGNUP: "/customerportal/terms_of_service_signup",
};
