export const ROUTE = {
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  ALERT: "/alert",
  DEVICES: "/devices",
  HISTORY: "/history",
  RECIPIENTS: "/recipients",
  SHOP: "https://ocufiistore.com/",
  HELP: "https://www.ocufii.com/",
  DEVICEDETAILS: "/device_details",
  ACCOUNT: "/account",
  SETTINGS: "/settings",
  ALERT_DETAILS: "/alert_details",
  SAFETY_NETWORK: "/safety_network",
  PERSONAL_SAFETY: "/personal_safety",
  ADD_RECIPIENT: "/add_new_recipient",
  RESEND_EMAIL: "/resend_email",
  EMAIL_VERIFIED: "/email_verified",
  INVITE_CONTACT: "/invite_contact",
  ACCEPT_INVITE: "/accept_inivite",
  MAP: "/map",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
};
